Feature/2817 lightning 2017 q1
savaslabs/savaslabs.github.io pull request #226
Opened 2017-03-13 20:29 UTC by chrisarusso

2017-03-15 18:37 UTC, lrowang commented
This PR is extension of #225 . Changed to correct branch name.

2017-03-16 17:26 UTC, kostajh requested changes
Only "required" change from me is to use the relative link for a post on our site. Other than that, nice work!

2017-03-16 17:26 UTC, kostajh commented on _posts/2017-03-20-lightning-q1-2017.md
> +One of our core [philosophies](http://savaslabs.com/mission-and-values/#excel) at Savas Labs is to "_hold ourselves to a high and constantly improving standard_." To that end, we dedicate time each m
@lrowang should use a relative link, `/mission-and-values/#excel`

2017-03-16 17:26 UTC, kostajh commented on _posts/2017-03-20-lightning-q1-2017.md
> +The Web Development world evolves quickly, and keeping abreast of new tools and methodologies while simultaneously delivering client work is tough.
consider lowercasing "Web Development"? not sure if it should be capitalized, I usually don't.

2017-03-16 17:26 UTC, kostajh commented on _posts/2017-03-20-lightning-q1-2017.md
> +There are many useful tools available for interacting with a MySQL database. Since we've transitioned to Docker for our local development, we prefer one of the following techniques for manipulating d
maybe link "Docker for our local development" to our Docker tag on the website

2017-03-16 17:26 UTC, kostajh commented on _posts/2017-03-20-lightning-q1-2017.md
> +Another method is to connect PhpStorm directly to the database container using PhpStorm's Database Browser. Instead of SSHing into the container via the command line, this allows us to view DB tables
as noted earlier, replace "SSHing" with "opening a shell"

2017-03-16 17:26 UTC, kostajh commented on _posts/2017-03-20-lightning-q1-2017.md
> +Once connected, PhpStorm will display all the tables in a drop down in the Database Browser, which is useful for quickly glancing through all the tables! You'll also be able to run SQL queries within
and you get useful code completions when writing database queries

2017-03-16 17:26 UTC, kostajh commented on _posts/2017-03-20-lightning-q1-2017.md
> +*There is a Desktop version for those who prefer using the full application. However the free desktop version limits recordings to 3 minutes.
need to close the italics on this sentence

2017-03-16 22:46 UTC, dmurphy1 commented on _posts/2017-03-20-lightning-q1-2017.md
> +[PhpMyAdmin](https://www.phpmyadmin.net/) is a great tool that provides a useful interface for visualizing and interacting with a MySQL database. [Docker4drupal](https://github.com/wodby/docker4drupa
Hi @lrowang - Docker4Drupal has unfortunately changed their template so can we remove the referenes to Docker4Drupal in this post? The PHPMyAdmin container isn't dependent on Docker4Drupal at all, I just got my inspiration from them! If you're curious, this is the [latest Docker4Drupal template](https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L61).

2017-03-17 21:19 UTC, lrowang commented on _posts/2017-03-20-lightning-q1-2017.md
> +[PhpMyAdmin](https://www.phpmyadmin.net/) is a great tool that provides a useful interface for visualizing and interacting with a MySQL database. [Docker4drupal](https://github.com/wodby/docker4drupa
Thanks for catching that @dmurphy1 ! I made the fix!

2017-03-20 15:40 UTC, lrowang commented
Deploying for now! Using basic asciinema video for now and we'll revisit the updated teleconsole gif/video soon!

2017-03-20 15:40 UTC, merged