Issue #4731: add job postings
savaslabs/savaslabs.github.io pull request #314
Opened 2017-11-03 20:58 UTC by AnneTee

Fixes issue [#4731](https://pm.savaslabs.com/issues/4731)

## Summary of changes

1. Builds the basic page layout and styles. This layout can be used with markdown files to create text-based pages similar to blog posts (but much simpler obviously). Basic pages can include a hero image and a CTA region in addition to the page title and body.
2. Adds a basic page template in the `_templates` directory with instructions for creating one
3. Adds `/jobs`. I thought the hero image was well-suited to a general jobs page, but if you don't want to spend the time filling this out yet, I can move it to the marketing director page.
4. Adds `/jobs/director-of-marketing`. 

## Notes

All copy is a draft and will need to be updated. Enjoy the corporate ipsum!

## To test

- [ ] Pull this and run `gulp clean && gulp serve`
- [ ] Check out http://localhost:3000/jobs/ and http://localhost:3000/jobs/director-of-marketing/
- [ ] Ensure things look good at various screen sizes

Feedback welcome!

### Pull request reviewer

As the reviewer, I have verified the following:

- [ ] I have tested the PR locally and/or in a staging environment

2017-11-03 21:09 UTC, chrisarusso commented
First thing, corporate ipsum is _AMAZING_ (read: I say half these things)... more to come.

2017-11-03 21:17 UTC, chrisarusso commented
should update "we're hiring" link on /company/, more next week, just didn't want to lose this!

2017-11-09 21:53 UTC, chrisarusso requested changes
1) Please review my copy updates
2) I think a header image for the Marketing Director page would be nice as well. I will be linking to it from off-site so many won't see the careers page
3) I still need to update copy on Marketing Director page - just a note

2017-11-13 15:30 UTC, chrisarusso approved these changes

2017-11-13 15:45 UTC, AnneTee commented on _pages/careers.md
> +At Savas Labs, we focus on the long-term with both those we partner with as well as our internal team. We have a core set of [values](company/mission-and-values/) that unite us, yet celebrate that wh
@chrisarusso You need a leading / in the link to the mission & values page

2017-11-13 15:45 UTC, AnneTee commented on _pages/careers.md
> + - generous PTO
Let's capitalize the first letter of each bullet point

2017-11-13 21:49 UTC, merged